### ISSUE TITLE
Script the setup of causal web on EC2 machine

### ISSUE THREAD

**Issue by espinoj** [bd2kccd/ccd-web#11]

**Comment by yuanzhou** [comment]
Things need to be covered in the bash script:
- upload the `causal-web.jar` to the mounted EBS volume
- update java 1.7 to 1.8 in order to use `causal-web.jar`
- install and config MySQL, create MySQL user account (used in ccd config) then create `ccd` database
- if run on a different port other than 80, need to enable the port by editing **Network Security Groups** via AWS console

**Comment by yuanzhou** [comment]
Created post install bash script, and uploaded to S3 bucket. Configured CfnCluster to read this script from S3 and run it on master node.

So far this script does the following:

```
#!/bin/bash

# Install Java Runtime 1.8
yum -y install java-1.8.0

# Then use the alternatives command to make Java 1.8 the default.
alternatives --config java <<< 2

# Let's also remove Java 1.7
yum -y remove java-1.7.0-openjdk

# Install MySQL server
yum -y install mysql-server

# Start MySQL
service mysqld start
```

Since this script is the post install script, CfnCluster will run it on all the cluster nodes. I verified the results on both Master node and compute node.

**Comment by yuanzhou** [comment]
Since only the master node needs MySQL, no need to install it via the CfnCluster post install script.
