### ISSUE TITLE
Create a jar resource with all dependencies

### ISSUE THREAD

**Issue by espinoj** [bd2kccd/ccd-web#12]

**Comment by yuanzhou** [comment]
The `causal-web-1.2.1.jar` contains all dependencies (mail, job-queu, db, commoms) except the `causal-cmd-5.3.0-SNAPSHOT-jar-with-dependencies.jar` (placed in `workspace/lib`). Is there a way of having only one final jar file?

**Comment by yuanzhou** [comment]
Since we've clarified this question, I'll let @kvb2univpitt create that script to generate the two jar files. Thanks @kvb2univpitt

**Comment by yuanzhou** [comment]
@kvb2univpitt when you get a chance to work on this, can you also put the properties files outside the causal-web jar file? Because the users will need to specify the port number and base URI, as well as the MySQL username/password. I can have MySQL installed using the post-install script, but I won't be able to set the usrname/password for the users via the bash script. So there are always user activities needed.

**Comment by yuanzhou** [comment]
After some thoughts, I think the desired file structure on cluster master node should look like this:

```
causal-web
 |-- application.properties
 |-- application-hsqldb.properties
 |-- application-mysql.properties
 |-- causal-web-1.2.1.jar
 |-- causal-web-install.sh
 |-- causal-web-start.sh
 `--ccd.properties
```

This allows the users to edit those configurations easily, then run `causal-web-install.sh` to install MySQL server and start the server, also chkconfig to make it auto start on reboot.

Then run `causal-web-start.sh` to trigger the jar file, may add extra commands there.

**Comment by yuanzhou** [comment]
Discussed during today's meeting, since we'll just need the released version of the jar files and properties files, there's no need to create a script to generate the jars.

**Comment by kvb2univpitt** [comment]
No longer required.
