### ISSUE TITLE
Test EBS nfs mount to cfncluster

### ISSUE THREAD

**Issue by espinoj** [bd2kccd/ccd-web#14]

**Comment by yuanzhou** [comment]
CfnCluster allows to use an existing EBS volume ID during the cluster creation, and it will be attached to the master node, then mounted to the `/shared` directory. Other compute nodes are able to access/share the data via NFS. We can also let CfnCluster create the EBS volume on the fly by specifying the volume type and size, or from an EBS snapshot. 

For testing purpose, I created an EBS volume(gp2 type, 5GB size) via the AWS console. Then specified the volume ID in CfnCluster config, and this EBS block was attached and mounted successfully. Successfully submitted jobs to run `causal-cmd.jar` via Slurm and all resulting files are store in the shared directory. Reboot and stop/start also work since the mountpoint entry was added to `/etc/fstab`.
