### ISSUE TITLE
Disable Annotation Icon When Annotation Service is Disabled  

### ISSUE THREAD

**Issue by yuanzhou** [bd2kccd/ccd-web#33]
I disabled the annotation service profile in `application.properties`  but the annotation icon still shows up in the Causal Web UI.

![capture](https://cloud.githubusercontent.com/assets/195873/20531586/34eb0db2-b0a5-11e6-83e9-a36714bb500c.PNG)

FYI @marksilvis I've talked to @kvb2univpitt and he said he'll make the change in causal web. Just wanted to track this on github.

**Comment by marksilvis** [comment]
The annotation profile is there only to load `application-annotations.properties`. It's assumed that annotations will always be a part of Causal-Web, given that its an integral part of the service.

This will also be changed in the next iteration of Annotations and Causal-Web, since I am changing the Annotations code to allow importing it as a dependency (i.e., no network calls, authentication, or annotation profile).

This was just an FYI. I do think that it would be a good idea to remove the Annotations button when the profile is not present; however, it won't be a problem when Annotations 1.0 is finished and being used.

**Comment by kvb2univpitt** [comment]
Anything that is always be a part of causal-web should never be made into a profile.  Profile should only be used to turn on and off features.  Annotation, in this case, is a feature that should be able to turn on and off to run on system that does not have the annotation service running.  This might be different in the next release.

I will working on this.

**Comment by kvb2univpitt** [comment]
Done.  It will be in v1.3.1.
